print('第一節')
print()
print('hello world')
print()
print('出現了helloworld，注意print框內用單引雙引號都可以，但要一直使用不要換來換去')
print()
print()
print('第二節')
print()
name = input('你的大名：')
print('咩料啊')
print(name)
print()
print('出現你的大名輸入框，顯示你的大名輸入結果')
print()
print()
print('第三節')
print()
print('print括弧可以做空格，在print括弧內輸入右斜槓n是換行\n例如')
print()
print('叼你老母 \n臭化西')
print()
print('結果如上')
print()
print()
print('第四節')
print()
print('print打印命令可用於顯示計算錯誤，沒有錯誤的不會顯示\n例如')
print()
print('Adding number')
x = 10 + 2
print('Performing division')
y = x / 0
print('Math complete')
print()
print('則會在結果中出現除數不能等於0的錯誤提示，算式沒有問題則不會提示。並且輸入那些“adding number”“performing division”有助于排查debug時可以知道是哪一行有問題')
